### ISSUE TITLE
Styling Problem with Elementor Template Block

### ISSUE THREAD

**Issue by ghost** [MjHead/jet-ajax-container#1]
Hi, thank you so much for considering my feature request.

I've been able to test the plugin on a test site: [https://sandbox.okparfait.dev/](https://sandbox.okparfait.dev/)

I'm testing with several blocks, and it seems to work very well. Great job!

So far, I've only found one issue: when I use the "Template" block from Elementor, the styling doesn't display correctly ([see page 2](https://sandbox.okparfait.dev/ajax-container-2/)).

What's odd is that on page 1, the styling of the template block displays correctly when it's loaded outside the AJAX Container.

**Comment by MjHead** [comment]
Thanks for the feedback, I'll take a look in 1-2 days
